@startuml helloworld
!RELATIVE_INCLUDE = "."
!include c4/C4_Context.puml

title Hello World

Person(user, "Пользователь", "Проверяет рендер C4")
System(hello, "Hello World", "Минимальная схема для проверки PlantUML")

Rel(user, hello, "Открывает")

SHOW_LEGEND()
@enduml
